propeller_control:
  ros__parameters:
    linear_pid_gain_kp: 1.0 #float
    linear_pid_gain_ki: 1.0 #float
    linear_pid_gain_kd: 1.0 #float
    linear_pid_gain_i_min: -1.0 #float
    linear_pid_gain_i_max: 1.0 #float
    linear_pid_gain_antiwindup: False #bool
    anguler_pid_gain_kp: 1.0 #float
    anguler_pid_gain_ki: 1.0 #float
    anguler_pid_gain_kd: 1.0 #float
    anguler_pid_gain_i_min: -1.0 #float
    anguler_pid_gain_i_max: 2.0 #float
    anguler_pid_gain_antiwindup: False #bool
    hull_width: 1.0 #float